### PR TITLE
docs: document build resolution in different ecosystems

### PR DESCRIPTION
**Pull request by algomaster99**
We document algorithms used used in different build ecosystems to resolve dependency.

### CODE REVIEW

**Comment by algomaster99** [comment]
@ericcornelissen could you please write about `npm`?
@javierron could you please write about `go`?

**Comment by algomaster99** [comment]
@danielwis could you write about Rust?

**Comment by monperrus** [comment]
thanks @algomaster99

**Comment by Stamp9** [comment]
@Stamp9 PYPI

**Pull request merged**
